webdav:
  url: "https://"
  username: ""
  password: ""
  backupDir: ""
mysql:
  username: "root"
  password: ""
blacklist:
- information_schema
- performance_schema
- mysql
- phpmyadmin
files:
- /etc/apache2/apache.conf
